### ISSUE TITLE
It's a tiny world

### ISSUE THREAD

**Issue by MartinMuzatko** [victorqribeiro/paintDraw#1]
hey! great thing you created here :)
I know it is just your personal experiment, but during long office hours, I discovered this and decided to doodle around for a bit.

Now I have nowhere to immortalize this 4th-grade like drawing, so I decided to come here.

![image](https://user-images.githubusercontent.com/2950505/60350202-609bb380-99c3-11e9-8d00-9bab9cca65c6.png)

I know it is not a big difference whether one doodled this in microsoft paint or in the browser. But it is your tiny realm and tiny world, and you have no track of what people might draw. So I thought it might be a good idea to give people a place here ;)

Cheers.

**Comment by victorqribeiro** [comment]
I love this. thank you so much for sharing
